### ISSUE TITLE
As a callback

### ISSUE THREAD

**Issue by majimboo** [0rpc/zerorpc-node#44]
I'm trying to do something like:

    Network.hookPacket(0x0000, onKeepAlive);

    function onKeepAlive(...

Now I wanted to use zerorpc like:

    Network.hookPacket(0x0000, Login.invoke('onKeepAlive'));

But I guess it gets executed instead of being a callback. So how do you think this could work with zerorpc?

**Comment by bombela** [comment]
You probably want to use a closure: Network.hookPacket(0x0000, function() { Login.invoke('onKeepAlive') });

But don't trust me on this, and go lookup on stackoverflow, my
