### ISSUE TITLE
Bidirectional

### ISSUE THREAD

**Issue by fuson** [0rpc/zerorpc-node#49]
Is it possiable?

**Comment by bombela** [comment]
Correct. Note that the protocol technically doesn't forbid it, it is simply not exposed in anyway, because it hard to get the API right without re-implementing the BSD stream socket API ;)

**Comment by ajitam** [comment]
I need to implement bidirectional communication between PY and NodeJS.
What do you think - is it better to use "zerorpc" with two servers/clients or just plain "zmq"?
