### ISSUE TITLE
Fails to build with Node v4.1.0

### ISSUE THREAD

**Issue by pensierinmusica** [0rpc/zerorpc-node#60]
The problem seems related to the `msgpack` module. I've opened an issue there too:
https://github.com/msgpack/msgpack-node/issues/27

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/nvm/versions/node/v4.1.0/bin/node" "/usr/local/Cellar/nvm/versions/node/v4.1.0/bin/npm" "install" "zerorpc"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! msgpack@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the msgpack@0.2.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the msgpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls msgpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ale/Dropbox/Docs/Good Karma/Projects/Distilled/code/back/koa/npm-debug.log
```

What worries me a bit, looking at the other `msgpack` issues is that the build seems to fail on many Node versions: https://github.com/msgpack/msgpack-node/issues/

Should this module be swapped for another Node JS version of msgpak, or be substituted entirely with `JSON.stringify` and `JSON.parse`? The latter would produce slightly longer strings, but should be way faster with current implementation (as mentioned in [`msgpack-node` docs](https://github.com/msgpack/msgpack-node/blob/master/README.md)).

**Comment by zachizi** [comment]
So… weird stuff going on here… there is both a [pgriess/node-msgpack](https://github.com/pgriess/node-msgpack) _and_ [msgpack/msgpack-node](https://github.com/msgpack/msgpack-node) repo and it seems the former actually gets more attention.

There is a PR right now on the pgriess repo that might update msgpack to work with nan > 2.0.0.  https://github.com/pgriess/node-msgpack/pull/62  as you can see there are conflicts (undefined support) and the original author of that fork wants to fix.

I don't know where that's going so I did this: https://github.com/zachizi/node-msgpack.  It's just all the Nan stuff without the undefined support.  It's failing a test though "unpacking a buffer with extra data doesn't lose the extra data" and that's probably where I'll leave it.

**Comment by zachizi** [comment]
Should be fixed with the merge of this PR https://github.com/msgpack/msgpack-node/pull/26

**Comment by godsflaw** [comment]
new msgpack merged, version bumped to 1.0.0, and pushed to npm

**Comment by zachizi** [comment]
@godsflaw thanks!

**Comment by bombela** [comment]
zerorpc uses msgpack to be cross-language. This means we cant get rid of msgpack. Its fine switching to a different msgpack implementation if needed though.
