### ISSUE TITLE
Error when installing new release

### ISSUE THREAD

**Issue by razvip91** [0rpc/zerorpc-node#63]
Hi there,

I'm trying to install the new release of 0rpc and can't. Apparently, the new version of msgpack added to package.json (msgpack@1.0.2) doesn't install on all versions of node. What exactly are the prerequisites now?

**Comment by bombela** [comment]
msgpack@1.0.2 should at least build on node 0.12.7 to 4.1.1. Could you problem be related to: msgpack/msgpack-node#29?

**Comment by razvip91** [comment]
I see. So node 0.10.37 is a no-no. The comment of the new release is misleading, though :)). 
But is it really necessary to upgrade nodejs? Can't I just upgrade the C++ library?

**Comment by bombela** [comment]
Yeah, sorry for the confusion, I guess the catch was in the "almost" in my comment ;)

Looking at https://github.com/nodejs/LTS/ v0.10 is supported until 2016-10-01. I guess if you can make msgpack work on v0.10 that would do the tricks :)

**Comment by razvip91** [comment]
OK, thanks for the hints. But the end result will eventually be to upgrade the nodejs version to, at least, 0.12.7 :dart:
