### ISSUE TITLE
Installation fails on Centos 7.1

### ISSUE THREAD

**Issue by sernapallyanurag** [0rpc/zerorpc-node#73]
I am unable to install `Zerorpc` on centos 7.1.

``

> msgpack@1.0.2 install /lib/node_modules/zerorpc/node_modules/msgpack
> node-gyp rebuild
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/roo
> t/.node-gyp/0.10.42"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/lib/node_modul
> es/zerorpc/node_modules/msgpack/.node-gyp"
> make: Entering directory `/usr/lib/node_modules/zerorpc/node_modules/msgpack/build'
>   CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
>   CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
>   CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
>   CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
>   CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
>   AR(target) Release/obj.target/deps/msgpack/msgpack.a
>   COPY Release/msgpack.a  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
> ../src/msgpack.cc: In function`void v8_to_msgpack(v8::Handlev8::Value, msgpac
> k_object_, msgpack_zone_, size_t)':
> ../src/msgpack.cc:126:93: error: could not convert `v8obj' from`v8::Handle<v8::
> Value>' to `v8::Local<v8::Value>' mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(v8obj, Nan::Encoding::UTF8));             ^
> ../src/msgpack.cc:129:94: error: could not convert`v8obj' from `v8::Handle<v8::
> Value>' to`v8::Localv8::Value'
>          Nan::DecodeWrite((char_)mo->via.str.ptr, mo->via.str.size, v8obj, Nan::
> Encoding::UTF8);
> ../src/msgpack.cc:136:94: error: could not convert `result' from`v8::Handle<v8:
> :Value>' to `v8::Local<v8::Value>'
>          mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(result, Nan::
> Encoding::UTF8));
> ../src/msgpack.cc:139:95: error: could not convert`result' from `v8::Handle<v8:
> :Value>' to`v8::Localv8::Value'
>          Nan::DecodeWrite((char_)mo->via.str.ptr, mo->via.str.size, result, Nan:
> :Encoding::UTF8)
> make: **\* [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
> make: Leaving directory `/usr/lib/node_modules/zerorpc/node_modules/msgpack/build'
> gyp ERR! build error
> gyp ERR! stack Error:`make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_module
> s/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
> gyp ERR! System Linux 3.10.0-229.4.2.el7.x86_64
> gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/nod
> e-gyp.js" "rebuild"
> gyp ERR! cwd /usr/lib/node_modules/zerorpc/node_modules/msgpack
> gyp ERR! node -v v0.10.42
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok/lib
> └── (empty)

npm ERR! Linux 3.10.0-229.4.2.el7.x86_64
npm ERR! argv "node" "/bin/npm" "install" "-g" "zerorpc"
npm ERR! node v0.10.42
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE

npm ERR! msgpack@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msgpack@1.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the msgpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs msgpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls msgpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

``

**Comment by bombela** [comment]
Looks like msgpack failed to build. Try to get msgpack to build first. I
suspect msgpack requires some version of nodejs.
