### ISSUE TITLE
Servers - Adding methods after instantiation. 

### ISSUE THREAD

**Issue by jacktuck** [0rpc/zerorpc-node#74]
Is it possible to add methods to the server once instantiated?

Something like this, perhaps:
```
var zerorpc = require("zerorpc");

var server = new zerorpc.Server();

server.add('addMan', function(sentence, reply) {
  reply(null, sentence + ", man!");
})
```

If not currently possible, would you be open to a PR to add such functionality?

**Comment by bombela** [comment]
It is not possible, and not intended to be. When a service is running, its API shouldn't change. That's a design decision to keep things simpler across languages.

Why would you want such functionality? What are you trying to achieve?
