### ISSUE TITLE
Trouble with npm install zerorpc

### ISSUE THREAD

**Issue by zx33** [0rpc/zerorpc-node#79]
There are some trouble while installing zerorpc.

Here are the outputs:
`gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andybear/node_modules/zerorpc/node_modules/zmq
gyp ERR! node -v v4.3.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "zerorpc"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.`

It shows that "No package 'libzmq' found", but I have installed and can get the version by using 'pkg-config --modversion libzmq'. So what should I do?

Here is the file of additional output - npm-debug.log.
[npm-debug.txt](https://github.com/0rpc/zerorpc-node/files/675487/npm-debug.txt)

**Comment by bombela** [comment]
Sadly, I have no experience with MacOS, I can merely suggest to double check your library path?

**Comment by bombela** [comment]
Maybe try the solution mentioned at the end of #75?

**Comment by chlrAndyBear** [comment]
I don't think it's the problem of version of Node....

npm ERR! node v4.3.2
npm ERR! npm v2.14.12

I will try to check my library path....

Thx~

**Comment by mjhenkes** [comment]
Try `brew install zeromq` Seems like you need it installed first or else npm install of zerorpc will fail.

**Comment by purplekrayons** [comment]
First, install [Brew](brew.sh)

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Then, install both `zeromq` and `pkgConfig`:

```
brew install pkgConfig
brew install zeromq
```

I have tried what I feel like is a million things, just trust me when I say use Brew.

I would also recommend you install `node-gyp` globally.

`sudo npm install -g node-gyp`

Then try rebuilding your project.

**Comment by purplekrayons** [comment]
Please close this -- open since Dec 2016.

**Comment by lzkelley** [comment]
I'm trying to create a packaged app that uses `zerorpc-node`, but in the distribution I'm running into this same error.  Shouldn't `npm` install the dependencies itself?  @bombela @purplekrayons
