### ISSUE TITLE
Setting heartbeatInterval is not working.!

### ISSUE THREAD

**Issue by Gowtham95india** [0rpc/zerorpc-node#85]
I'm constructing 

```javascript
var zerorpc = require("zerorpc");
var client = new zerorpc.Client({heartbeatInterval: 0});
client.connect("tcp://127.0.0.1:4242");
```
But it seems, it has no effect?

I'm still getting.. ERROR: HeartbeatError: Lost remote after -10000ms

**Comment by bombela** [comment]
You are asking for a heartbeat of 0 second. zerorpc returns a `Lost remote` error after two missed heartbeats. Thus zerorpc waits 0*2 = 0 seconds for the server's heartbeat. Also not the heartbeat must be identical between the server and the client. Else one will think the other is not responding.

In normal operation you shouldn't need to change the default heartbeat interval.

**Comment by Gowtham95india** [comment]
@bombela Thanks for the update.

**Comment by johaven** [comment]
On Python side is possible to disable hearbeat but not in this module (0rpc/node).
There is a reason ?

Client side:
```javascript
var heartbeat = options.heartbeatInterval || DEFAULT_HEARTBEAT;
```

Server side:
```javascript
var heartbeat = heartbeat || DEFAULT_HEARTBEAT;
```

If we pass null value, we got the default value :(

**Comment by bombela** [comment]
Yeah logic in the code doesn't support this. PRs are welcome :)
