### ISSUE TITLE
Millisecond-resolution timeouts

### ISSUE THREAD

**Issue by maxcountryman** [0rpc/zerorpc-node#89]
I'm curious if there's a reason timeouts cannot be in rendered in millisecond resolution?

My use-case is an application where latency is key concern (we're aiming for sub-millisecond response times) and we would much rather timeout than wait for a slow response.

**Comment by bombela** [comment]
timeouts are floating point seconds. you do have millisecond resolution. `0.1` should give you a 100ms timeout for example.

**Comment by maxcountryman** [comment]
Thank you.
