### ISSUE TITLE
Page refreshes when invoking a method

### ISSUE THREAD

**Issue by cipiasentini** [0rpc/zerorpc-node#93]
Hi, I wanted to know how can I handle this problem. I want to be able to invoke a method to change the webpage content but without the whole page refreshing when it is done.

**Comment by bombela** [comment]
Hello, this is not a zerorpc specific question. I think you must look into
web browser, page side JavaScript API.

**Comment by cipiasentini** [comment]
It actually has to do with the way zerorpc handles the response, or does the execution. Here I uploaded a video of how my app is behaving and the code being used [https://youtu.be/Gqo_QpsKMNU](https://youtu.be/Gqo_QpsKMNU). If I comment out the part when I invoke the process inicializar there is no refreshing

**Comment by bombela** [comment]
I am just the maintainer of the node version. Note that zerorpc-node was written for nodejs. In what context are you running it? Could it be that zerorpc is raising an exception, and you have some sort of system that automatically refresh the page on error?

**Comment by cipiasentini** [comment]
I've solved the issue.. It was so dumb of me, I have been using electron-reload for fast prototyping and my app every time it starts was changing a file (which was within the project folder) that was causing the refresh... You can mark it as solved :). Now I'm having another problem but this time is with the server not wanting to start when I package the electron app but I'll be reporting this issue somewhere else it's not the server scope. Thanks for your help

**Comment by bombela** [comment]
Ahah nice one. Small mistakes like that are always the worst to debug. Thank you for replying back here!
