### ISSUE TITLE
Crash in Windows 10

### ISSUE THREAD

**Issue by purplekrayons** [0rpc/zerorpc-node#94]
node: 9.1.0
zerorpc: 0.9.7
electron: 1.7.9
windows 10 pro

It looks like zerorpc, or one of its dependencies, may be causing my electron app to crash upon launching in Windows 10. Console is immediately disconnected from browser window and nothing is being printed. 

If I `npm uninstall` zerorpc, or otherwise just comment out my `var zerorpc = require('zerorpc')` everything works as expected.

Any ideas how I can go about better debugging / determining whats causing this?

**Comment by purplekrayons** [comment]
Linking a related [StackOverflow](https://stackoverflow.com/questions/47054351/node-js-zerorpc-crashes-on-windows-10).

**Comment by purplekrayons** [comment]
Closing issue -- opted to move away from zerorpc.

**Comment by bombela** [comment]
I have no experience with development on Microsoft Windows. Do you know if you get the same crash on Linux?
